import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

import styled from 'styled-components';
import { OpenInNew } from '@material-ui/icons';

import Layout from '@components/Layout/index';

const LinkContainer = styled.div`
  display: flex;
  align-items: center;
  margin-bottom: 20px;

  & a {
    font-size: 24px;
    font-weight: bold;
    margin-right: 8px;
    color: rgba(0, 0, 0, 0.5);

    & :hover {
      color: rgba(0, 0, 0, 0.87);
    }

    &:visited {
      color: rgba(0, 0, 0, 0.5);
    }
  }

  & svg {
    fill: rgba(0, 0, 0, 0.5);
  }
`;

function TermsOfUso() {
  return (
    <Layout>
      <Head>
        <title>Kwadros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pdf-container">
        <LinkContainer>
          <Link href="/politicas-de-privacidade">Políticas de Privacidade</Link>
          <OpenInNew />
        </LinkContainer>
        <LinkContainer>
          <Link href="/termos-de-uso">Termos de Uso</Link>
          <OpenInNew />
        </LinkContainer>
      </div>
    </Layout>
  );
}

export default TermsOfUso;
