import React, { FormEvent, useState } from 'react';
import Head from 'next/head';
import { useRouter } from'next/router';
import { IconButton } from '@material-ui/core';
import { ChevronLeft } from '@material-ui/icons';

import { Container, Box, CardBox, MainBtn, FormInput, StepsHeader, Transition1, Transition2 } from '../components/GetStarted/styles';

function GetStarted() {
  const router = useRouter();

  const [step, setStep] = useState(0);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');

  function handleBack() {
    if (step) {
      setStep(step - 1);
    }
  }

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (step === 1) {
      return router.push('/review');
    }
    return setStep(step + 1);
  }

  return (
    <>
      <Head>
        <title>Kwadros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Container>
          <Box>
            <StepsHeader>
              <IconButton onClick={handleBack}>
                <ChevronLeft />
              </IconButton>
              <span>{step + 1} / 2</span>
            </StepsHeader>
            <CardBox onSubmit={(e) => handleSubmit(e)}>
              {step === 0 ? (
                <Transition1>
                  <h2>Deixe-nos te conhecer</h2>
                  <FormInput
                    required
                    type="name"
                    value={name}
                    onChange={({ target }) => setName(target.value)}
                    placeholder={'Qual é o seu nome?'}
                    maxLength={20}
                  />
                  <MainBtn type="submit">Continuar</MainBtn>
                </Transition1>
              ) : step === 1 ? (
                <Transition2>
                  <h2>Olá, {name}!</h2>
                  <FormInput
                    required
                    type="email"
                    value={email}
                    onChange={({ target }) => setEmail(target.value)}
                    placeholder={'Qual é o seu email?'}
                    maxLength={80}
                  />
                  <MainBtn type="submit">Escolher Fotos</MainBtn>
                </Transition2>
              ) : (
                ''
              )}
            </CardBox>
          </Box>
        </Container>
      </>
    </>
  );
}

export default GetStarted;
