import React, { useState, useEffect, useRef, FormEvent, SyntheticEvent } from 'react';
import { useSelector, useDispatch } from '@hooks';

import Head from 'next/head';
import { setName, setEmail, setStep } from '@modules/user/actions';
import { useRouter } from 'next/router';
import { IconButton } from '@mui/material';
import { ChevronLeft } from '@mui/icons-material';

import { Container, Box, CardBox, MainBtn, FormInput, StepsHeader, Transition1, Transition2 } from '../components/GetStarted/styles';

import Loading from '@components/Loading/animation';

function GetStarted() {
  const dispatch = useDispatch();
  const router = useRouter();

  const step = useSelector((state) => state.user.step);
  const name = useSelector((state) => state.user.name);
  const email = useSelector((state) => state.user.email);

  const [_name, _setName] = useState(name);
  const [_email1, _setEmail1] = useState(email);
  const [_email2, _setEmail2] = useState(email);

  const emailRef = useRef<any>(null);

  function handleNameChange(e: SyntheticEvent & { target: HTMLInputElement }) {
    e.preventDefault();
    const fullName = e.target.value.split(' ').filter((e) => e !== '');

    if (fullName.length < 2) {
      e.target.setCustomValidity('Por favor, insira seu nome completo');
    } else {
      e.target.setCustomValidity('');
    }

    _setName(e.target.value);
  }

  function handleEmailChange(e: SyntheticEvent & { target: HTMLInputElement }) {
    e.preventDefault();

    if (e.target.value !== '' && e.target.value !== _email1) {
      e.target.setCustomValidity('Os dois emails devem ser iguais');
    } else {
      e.target.setCustomValidity('');
    }

    _setEmail2(e.target.value);
  }

  function handleBack() {
    if (step) {
      return dispatch(setStep({ payload: step - 1 }));
    }
    return router.push('/');
  }

  function handleSubmit(e: FormEvent) {
    e.preventDefault();

    if (step === 1) {
      if (_email1 !== _email2) {
        return;
      }

      dispatch(setEmail({ payload: _email2 }));
      return dispatch(setStep({ payload: step + 1 }));
    }

    dispatch(setName({ payload: _name }));
    return dispatch(setStep({ payload: step + 1 }));
  }

  useEffect(() => {
    if (step === 2) {
      router.push('/review');
    }

    //eslint-disable-next-line
  }, [step]);

  return (
    <>
      <Head>
        <title>Kwadros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Container>
          <Box>
            <StepsHeader>
              <IconButton onClick={handleBack}>
                <ChevronLeft />
              </IconButton>
              <span>{step + 1} / 2</span>
            </StepsHeader>
            <CardBox onSubmit={(e) => handleSubmit(e)}>
              {step === 0 ? (
                <Transition1>
                  <h2>Deixe-nos te conhecer</h2>
                  <FormInput
                    required
                    type="name"
                    value={_name}
                    onChange={handleNameChange}
                    placeholder={'Qual é o seu nome?'}
                    maxLength={40}
                  />
                  <MainBtn type="submit">Continuar</MainBtn>
                </Transition1>
              ) : step === 1 ? (
                <Transition2>
                  <h2>Olá, {name}!</h2>
                  <FormInput
                    required
                    type="email"
                    value={_email1}
                    onChange={({ target }) => _setEmail1(target.value)}
                    placeholder={'Insira seu email'}
                    maxLength={80}
                  />
                  <FormInput
                    id="email2"
                    ref={emailRef}
                    required
                    type="email"
                    value={_email2}
                    onChange={handleEmailChange}
                    placeholder={'Confirme seu email'}
                    maxLength={80}
                  />
                  <MainBtn type="submit">Escolher Fotos</MainBtn>
                </Transition2>
              ) : (
                <Loading fill />
              )}
            </CardBox>
          </Box>
        </Container>
      </>
    </>
  );
}

export default GetStarted;
