import React, { useState, useEffect, FormEvent } from 'react';
import { useSelector, useDispatch } from '@hooks';

import Head from 'next/head';
import { setName, setEmail, setStep } from '@modules/user/actions';
import { useRouter } from 'next/router';
import { IconButton } from '@material-ui/core';
import { ChevronLeft } from '@material-ui/icons';

import { Container, Box, CardBox, MainBtn, FormInput, StepsHeader, Transition1, Transition2 } from '../components/GetStarted/styles';

import Loading from '@components/Loading/animation';

function GetStarted() {
  const dispatch = useDispatch();
  const router = useRouter();

  const name = useSelector((state) => state.user.name);
  const email = useSelector((state) => state.user.email);

  const [_name, _setName] = useState(name);
  const [_email, _setEmail] = useState(email);

  const step = useSelector((state) => state.user.step);

  function handleBack() {
    if (step) {
      return dispatch(setStep({ payload: step - 1 }));
    }
    return router.push('/');
  }

  function handleSubmit(e: FormEvent) {
    e.preventDefault();

    if (step === 1) {
      dispatch(setEmail({ payload: _email }));
      return dispatch(setStep({ payload: step + 1 }));
    }

    dispatch(setName({ payload: _name }));
    return dispatch(setStep({ payload: step + 1 }));
  }

  useEffect(() => {
    if (step === 2) {
      router.push('/review');
    }
  }, [step]);

  return (
    <>
      <Head>
        <title>Kwadros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Container>
          <Box>
            <StepsHeader>
              <IconButton onClick={handleBack}>
                <ChevronLeft />
              </IconButton>
              <span>{step + 1} / 2</span>
            </StepsHeader>
            <CardBox onSubmit={(e) => handleSubmit(e)}>
              {step === 0 ? (
                <Transition1>
                  <h2>Deixe-nos te conhecer</h2>
                  <FormInput
                    required
                    type="name"
                    value={_name}
                    onChange={({ target }) => _setName(target.value)}
                    placeholder={'Qual é o seu nome?'}
                    maxLength={20}
                  />
                  <MainBtn type="submit">Continuar</MainBtn>
                </Transition1>
              ) : step === 1 ? (
                <Transition2>
                  <h2>Olá, {name}!</h2>
                  <FormInput
                    required
                    type="email"
                    value={_email}
                    onChange={({ target }) => _setEmail(target.value)}
                    placeholder={'Qual é o seu email?'}
                    maxLength={80}
                  />
                  <MainBtn type="submit">Escolher Fotos</MainBtn>
                </Transition2>
              ) : (
                <Loading fill />
              )}
            </CardBox>
          </Box>
        </Container>
      </>
    </>
  );
}

export default GetStarted;
