import React from 'react';
import Head from 'next/head';

import Layout from '@components/Layout/index';

function Home() {
  return (
    <Layout>
      <Head>
        <title>Kwadros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pdf-container">
        <h1>Política de Privacidade</h1>
        <p>
          A presente Política de Privacidade contém as informações necessárias para que os Usuários da Plataforma Vve comercio de artigos
          recreativos e decorativos ltda, CNPJ 42430077/0001-41 (aqui nessa página referida como “KWADROS”) entendam a forma com a qual a
          Kwadros trata os dados pessoais dos Usuários, de acordo com o que estabelece a legislação aplicável (1. Nesta nova atualização a
          Kwadros fez a revisão de toda a sua “Política de Privacidade” para adequação às normas da Lei Federal nº. 13.709/2018, a chamada
          LGPD – Lei Geral de Proteção de Dados e garantir aos seus Usuários ainda maior transparência, confiabilidade e segurança das
          informações. Justamente por se preocupar com a privacidade de seus Usuários, a Kwadros tem o compromisso de preservá-la como uma
          de suas bases de atuação, com produtos desenvolvidos, desde o início, com o conceito “privacy by design”, que significa que todos
          os produtos e serviços desenvolvidos pela plataforma contemplam a privacidade desde seu nascedouro até a entrega ao consumidor.
          Antes de utilizar as nossas ferramentas e serviços, é preciso que você, Usuário, tome ciência de quais informações processamos
          para viabilizar a operação da Kwadros; para fins de cumprir o fundamento disposto no artigo 2º, inciso II, da LGPD, apresentamos
          os Termos de Uso da Kwadros que contém essas informações, como modo de propiciar uma “autodeterminação informativa”, quer seja a
          possibilidade de posse das informações, o Usuário ter a opção informada de usar ou não os serviços. Com essa transparência,
          adequação e finalidade, ao efetuar o pedido o consumidor confirma sua opção de uso e declara estar de acordo com nossa Política de
          Privacidade, que possui informações claras e completas sobre coleta, uso, armazenamento, tratamento e proteção de seus dados
          pessoais. Assim, antes de iniciar a sua experiência de Usuário, a Kwadros insiste para que você leia com atenção a Política de
          privacidade antes de se cadastrar ou mesmo navegar no site e plataforma da Kwadros. Para se adaptar às alterações legislativas e
          expectativas dos Usuários, a Kwadros poderá modificar a sua Política de Privacidade. Assim, é importante que você consulte nossa
          política regularmente. <h4>DEFINIÇÕES</h4> Os termos e expressões constantes deste item são empregados nesta Política de
          Privacidade com o mesmo significado atribuído abaixo: Dados Cadastrais – a filiação, o endereço (físico ou eletrônico), e a
          qualificação pessoal, entendida como nome, prenome, estado civil De acordo com o que dispõe a LGPD, em seu artigo 5º,
          considera-se: <h5>Dado Pessoal:</h5> informação relacionada a pessoa natural identificada ou identificável; a pessoa natural é a
          pessoa física e os dados que a identifica ou a tornam identificável são todos aqueles que possam ser usados direta ou
          indiretamente para identificar essa mesma pessoa, por exemplo: nome, documento de identidade, CPF, documento de identidade
          profissional, fotos e vídeos, e-mail, dados bancários, geolocalização, telefones, postagens em redes sociais, endereço de IP, etc.
          Dado Pessoal Sensível: dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou
          a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico,
          quando vinculado a uma pessoa natural; <h5>Dado anonimizado:</h5> dado relativo a titular que não possa ser identificado,
          considerando a utilização de meios técnicos razoáveis e disponíveis na ocasião de seu tratamento; neste caso, o dado pode ser
          armazenado, desde que não seja possível, através de ferramentas simples, reverter essa anonimização e tornar a pessoa
          identificável. <h5>Banco de dados:</h5> conjunto estruturado de dados pessoais, estabelecido em um ou em vários locais, em suporte
          eletrônico ou físico; ou seja, é o conjunto de informações que vinculam ou podem vincular uma pessoa natural e torna-la
          identificada ou identificável. <h5>Titular do dado pessoal:</h5> pessoa natural a quem se referem os dados pessoais que são objeto
          de tratamento; <h5>Tratamento de Dados Pessoais:</h5> toda operação realizada com dados pessoais, como as que se referem a coleta,
          produção, recepção, classificação, utilização, acesso, reprodução, transmissão, distribuição, processamento, arquivamento,
          armazenamento, eliminação, avaliação ou controle da informação, modificação, comunicação, transferência, difusão ou extração. A
          Kwadros, na qualidade de plataforma de e-commerce, coleta dados, os trata e armazena com observância das melhores ferramentas de
          segurança disponíveis no mercado, sendo, por definição um controlador e um operador de dados pessoais; é responsável pelas
          informações que compartilha com terceiros, fornecedores ou prestadores de serviços, tudo de acordo com os ditames da LGPD, seus
          princípios e requisitos, como pode ser observado nesta “Política de Privacidade”, a qual se enquadra nos termos da Lei Federal
          13.709/2018 (Lei Geral de Proteção de Dados) <h4>1) APLICAÇÃO DA POLÍTICA</h4> Esta Política de Privacidade se aplica a todos e
          quaisquer serviços, produtos e/ou ferramentas digitais disponibilizadas pela Kwadros em suas plataformas, website ou software.{' '}
          <h4>2) COLETA DE DADOS PESSOAIS E INFORMAÇÕES CADASTRAIS</h4> Para a correta utilização da plataforma da Kwadros é imprescindível
          a coleta, armazenamento e processamento dos dados pessoais obtidos dos Usuários, a fim de possibilitar a prestação dos serviços
          ofertados através de sua Plataforma. Assim, é preciso que você concorde expressamente e de forma inequívoca com a possibilidade de
          a kwadros coletar, receber e armazenar, automaticamente, Dados Pessoais e informações em seus servidores sobre as atividades
          advindas do navegador dos usuários, incluindo geolocalização, endereços IP, cookies, leads ou outras sequências de caracteres
          identificadores, e ainda informações sobre as transações efetuadas por meio da plataforma. Alguns Dados Pessoais são
          obrigatoriamente colhidos pela Kwadros a fim de permitir a execução do contrato de serviços (Termos de Uso) firmado com o Usuário
          e a operacionalização da Plataforma. A utilização das ferramentas oferecidas pela Kwadros dados pessoais como nome completo, data
          de nascimento, documento de identificação (RG, CPF e/ou CNPJ), telefone, endereço e endereço eletrônico, bem como da criação de
          uma senha de acesso que será de seu conhecimento exclusivo. Pelo presente termo, o usuário declara-se ciente de que é de sua
          responsabilidade fornecer informações verdadeiras, exatas, atuais e completas quando realizar seu cadastro para acesso à
          Plataforma. A indicação de dados incompletos ou falsos é crime tipificado em lei e pode acarretar punições severas a quem as
          fornecer. A Kwadros também tem um EDP – Encarregado de Dados Pessoais, que é a pessoa responsável pela gestão destes dados e sua
          relação com os titulares; toda e qualquer informação ou solicitação feita, que guarde relação com os dados pessoais, será
          respondida pelo EDP, com a chancela da política de privacidade e transparência da Kwadros. É importante deixar claro que o
          Usuário, ao aceitar os termos de uso e a política de privacidade, apõe seu consentimento informado, ou seja, declara que concorda
          com a coleta, tratamento e armazenamento de seus dados, tudo conforme determina o inciso XII, do artigo 5º, da LGPD; também
          deixamos registrado que, a qualquer momento, o Usuário poderá revogar seu consentimento e solicitar à Kwadros sua anonimização ou
          descarte (eliminação), ou, ainda, informações de quais dados pessoais de sua titularidade estão armazenados em seus arquivos e
          bancos de dados e para qual finalidade específica. <h4>3) CONTROLE DOS DADOS CADASTRAIS PELOS USUÁRIOS</h4> Cada usuário tem
          controle sobre os Dados Cadastrais constantes no perfil criado na Kwadros, podendo acessá-los, atualizá-los e alterá-los mediante
          o uso de seu login e senha na Plataforma da Kwadros, que são individuais e conhecidos apenas pelo próprio usuário que deverá zelar
          pelo sigilo desses dados. A Kwadros não se responsabiliza pela forma como estes dados são usados pelo Usuário.{' '}
          <h4>4) INTERROMPIMENTO DA COLETA DE DADOS</h4> Caso o Usuário não queira ter seus Dados Pessoais coletados, a Kwadros recomenda
          que o Usuário não os forneça; como já informado acima, a Kwadros tem canais de comunicação com o Usuário que estão aptos a
          fornecer quais dados estão armazenados e as opções de anonimização e eliminação (descarte); o fornecimento ou não dos dados
          pessoais é uma opção do Usuário, que, ao concordar com o fornecimento, concorda com seu tratamento, desde que adequado à
          finalidade e dentro dos princípios legais fornecidos pelo artigo 6º, da LGPD. A Kwadros recomenda que os Usuários gerenciem a
          utilização dos cookies no seu navegador de internet, mantendo a funcionalidade habilitada e autorizada; a Kwadros também adverte
          que a habilitação e autorização para utilização de cookies tem como objetivo melhorar a experiência do Usuário, traçando um perfil
          mais qualificado que propicie um melhor conhecimento e uma relação mais adequada entre as partes, razão pela qual, caso o Usuário
          não tenha interesse nesta customização, deve desabilitar e não autorizar os cookies no campo específico da plataforma.{' '}
          <h4>5) COLETA E USO DOS DADOS PESSOAIS E INFORMAÇÕES COLETADOS</h4> Pela presente Política de Privacidade os Dados Pessoais e
          Cadastrais coletados, bem como quaisquer outras informações coletadas, poderão ser usados pela Kwadros para fins de comunicação da
          nossa equipe com os Usuários, a partir de envio de notificações sobre sua atividade com as ferramentas da Kwadros , bem como
          alertas e notificações do sistema; referida coleta está adstrita às finalidades descritas neste Termo e nos serviços prestados
          pela Kwadros e podem ser tratados para cumprimento de obrigação legal ou regulamentar, caso necessário, para execução de contratos
          atrelados aos dados, exercício regular de direito em processo judicial e em todas as hipóteses legais elencadas no artigo 7º,
          incisos I a X, da Lei 13.709/2018. Além disso, os Dados Pessoais e Cadastrais coletados, bem como quaisquer outras informações e
          registros de acesso às ferramentas da Kwadros, poderão ser armazenados, tratados, processados e utilizados por nós com as
          seguintes finalidades:
          <ol>
            <li>aperfeiçoar e sofisticar os serviços, produtos e ferramentas disponibilizados pela Kwadros;</li>
            <li>
              concluir as solicitações do Usuário e permitir o uso de determinadas funcionalidades dos seus produtos, serviços e/ou
              ferramentas;
            </li>
            <li>
              enviar aos Usuários, através de mensagens, informações relativas aos produtos, serviços, publicidade, promoções, banners e
              notícias da Kwadros;
            </li>
            <li>traçar perfis e tendências demográficas de uso dos seus produtos, serviços e/ou ferramentas;</li>
            <li>
              entrar em contato com o Usuário para confirmar informações que tenham sido fornecidas e solicitar o envio de informações que
              ainda estejam pendentes para que a Kwadros possa devidamente executar suas atividades;
            </li>
            <li>garantir que as funcionalidades dos seus produtos, serviços e/ou ferramentas se mantenham sempre úteis para o Usuário;</li>
            <li>proteger a segurança e a integridade da sua base de dados;</li>
            <li>oferecer serviços e/ou produtos de terceiros, conforme aplicável;</li>
            <li>Quando necessário para atender os interesses legítimos do controlador;</li>
          </ol>
          <h4>5.1) DADOS PESSOAIS E DIREITOS DOS USUÁRIOS</h4>
          Os Usuários têm o direito de receber informações claras e completas, sempre que formalmente solicitado, sobre dados pessoais
          eventualmente coletados e/ou processados pela Kwadros, esta solicitação deve atender ao que dispõe o artigo 9º e 18 a 22 da Lei
          13.709/2018. Os Usuários poderão, a qualquer momento, solicitar que a Kwadros exclua, retifique, corrija e restrinja o uso dos
          seus Dados Pessoais, inclusive fornecendo os Dados Pessoais solicitados em formatação adequada, estruturada e usual, nos termos da
          legislação aplicável. Fica assegurado aos Usuários exercerem seus direitos e apresentar reclamações junto às autoridades de
          proteção de dados competentes. Para o exercício de qualquer dos seus direitos atrelados aos dados pessoais eventualmente colhidos
          e processados pela Kwadros, bem como para enviar dúvidas e questionamentos, os Usuários deverão contatar a Kwadros através do
          e-mail contato@kwadros.com Os Usuários cujos dados pessoais foram colhidos e processados com base no consentimento concedido,
          poderão, a qualquer momento, solicitar que a Kwadros os retire, sem que isso afete a legalidade da coleta e processamento
          realizado. Caso o Usuário retire o consentimento ou solicite a exclusão de dados quando coletados e processados com fundamento no
          interesse legítimo e/ou necessidade para execução de contrato, este reconhece e aceita, desde já, que a Kwadros não será
          responsabilizada com relação a qualquer perda e/ou dano causado aos seus dados pessoais se o Usuário optar por retirar o
          consentimento. A Kwadros informa que deverá manter em seus arquivos certos dados pessoais colhidos em decorrência de obrigações
          legais impostas durante determinado tempo, mesmo que o Usuário solicite sua exclusão e/ou alteração. A título exemplificativo,
          dados vinculados a documentos fiscais, transações financeiras, CPF/CNPJ, nome completo e outros necessárias para identificar uma
          determinada operação financeira, tributária ou fiscal serão mantidos pela Kwadros mesmo que sua exclusão seja solicitada. A
          Kwadros garante aos seus Usuários envidar seus melhores esforços de forma a manter todos os dados pessoais coletados devidamente
          seguros, protegidos e confidenciais, em que pese ser inviável, tecnicamente, garantir a inviolabilidade dos dados no caso de
          eventuais ataques externos e falhas de sistema. Na hipótese de violação de dados pessoais, a Kwadros se compromete em informar os
          Usuários o ocorrido e quais dados foram violados, dentro do princípio da transparência e confiança que deve reger a relação entre
          Kwadros e seus Usuários. <h4>5.2) RESPONSABILIDADE DOS USUÁRIOS QUANTO À PROTEÇÃO DE DADOS COLETADOS</h4> Tendo em vista o modelo
          de negócios da Kwadros, ao utilizar a Plataforma, presume-se que o Usuário é o proprietário de um negócio e utiliza os serviços da
          Kwadros para comercializar seus produtos. Os dados pessoais dos clientes, colhidos pelos Usuários e eventualmente entregues à
          Kwadros serão processados e estarão sujeitos às regras de proteção de dados pessoais. Entretanto, os dados dos clientes dos
          Usuários estão sujeitos ao controle dos Usuários, tendo em vista que são responsáveis pela coleta dos dados pessoais junto aos
          seus clientes. Dessa forma, os Usuários concordam e reconhecem que são exclusivamente responsáveis por respeitar, integralmente, a
          legislação de proteção de dados aplicável, especialmente a Lei 13.709/2018 – Lei Geral de Proteção de Dados e o GDPR - Regulamento
          Geral sobre a Proteção de Dados 2016/679, caso o cliente que teve os dados coletados esteja localizado em um país pertencente à
          União Europeia. Mesmo que a Kwadros crie certas funcionalidades que poderão facilitar que seus Usuários se mantenham em
          conformidade com a legislação relativa à proteção de dados pessoais, como avisos padronizados de coleta de dados, os Usuários
          reconhecem que a Kwadros não atua ou oferta serviços de consultoria legal e jurídica de qualquer natureza, eximindo-a, desde já,
          de responsabilidade nesse sentido. A Kwadros recomenda que os Usuários obtenham previamente o aconselhamento jurídico e técnico
          adequado para se certificar que estão em conformidade com as leis e normas aplicáveis ao seu negócio, em especial, as relativas à
          proteção de dados pessoais. <h4>6) TRATAMENTO DOS DADOS PESSOAIS COLETADOS</h4> Todos os Dados Pessoais dos Usuários serão
          colhidos e processados nos termos da presente Política de Privacidade e serão armazenados na base de dados da Kwadros , até que o
          Usuário solicite que a Kwadros deixe de usar os Dados Pessoais. Os demais dados serão mantidos pela Kwadros pelo tempo que for
          necessário para o cumprimento das finalidades para as quais foram originalmente coletados, inclusive para o atendimento da
          legislação. A Kwadros declara que todos os dados colhidos serão armazenados em bancos de dados seguros, dentro das melhores
          práticas, com acesso restrito a funcionários, que estão sujeitos às regras de tratamento confidencial em relação às informações. A
          Kwadros poderá armazenar e tratar os Dados Pessoais coletados e demais informações coletadas em um servidor localizado no Brasil
          ou no exterior.
          <h4>7) DIVULGAÇÃO DOS DADOS A TERCEIROS</h4> O Usuário declara que entende e autoriza que a Kwadros poderá entregar os Dados
          Pessoais e Cadastrais, tais como seu nome completo e endereço eletrônico, ao Comprador, em caso de infração dos Termos de Uso que
          possa provocar danos a outros Usuários da Kwadros ou a terceiros. O Usuário concorda que, na tentativa de evitar atividades
          ilegais, em casos de suspeita de fraude, disputas, reclamação quanto ao conteúdo ou qualquer indício de ilícito cometido pelos
          Usuários, incluindo disseminação de spam e situações envolvendo ameaças em potencial à segurança física de alguém, os Dados
          Pessoais e Cadastrais dos Usuários envolvidos poderão ser fornecidos aos prejudicados. Em determinados casos, se considerar
          necessário, a Kwadros poderá fornecer os dados coletados aos órgãos e entidades que intervenham na investigação ou na resolução de
          disputas entre Usuários ou entre Usuários e terceiros, tais como: polícias e órgãos de secretaria de segurança, seguradoras,
          órgãos judiciais, juízos arbitrais e demais órgãos administrativos ou judiciais competentes. O Usuário concorda que a Kwadros
          poderá compartilhar os Dados Pessoais e Cadastrais coletados com os provedores de serviços terceirizados da Kwadros , a fim de
          permitir o desenvolvimento de suas respectivas atividades e possibilitar a melhoria dos serviços e operações da Plataforma, como
          por exemplo, mas sem se limitar, a serviços de: backup de dados, serviços de prevenção de fraude, provedores de serviços de e-mail
          e bancos de dados, emissão de notas fiscais, entre outros. A Kwadros exige de todos os prestadores de serviços com os quais
          compartilha os Dados Pessoais de Usuários, incluam em seus contratos disposições que garantam a devida proteção, sigilo e
          confidencialidade no processamento dos dados. O Usuário concorda, ainda, que, em caso de eventual operação societária que envolva
          a reestruturação da Kwadros , suas controladoras e controladas, bem como a aquisição e/ou venda de ações e ativos, os Dados
          Pessoais coletados poderão ser considerados um dos ativos comerciais a serem transferidos, ficando a Kwadros autorizada a
          transferir os Dados Pessoais e Cadastrais dos Usuários. Excluídas as hipóteses mencionadas nesta Política de Privacidade, os Dados
          Pessoais e Cadastrais, coletados diretamente pela Plataforma, bem como os registros de acesso à Plataforma (endereço de IP, data,
          hora e fuso horário) e os dados referentes às transações realizadas por meio da Plataforma, somente poderão ser revelados a
          terceiros nas seguintes hipóteses: • a pedido ou por autorização específica do próprio usuário; • em cumprimento de ordem judicial
          ou em razão de disposição legal; • para a proteção da vida ou da incolumidade física do titular, dos Dados ou de terceiros; e •
          para a tutela da saúde, em procedimento realizado por profissionais da área da saúde ou por entidades sanitárias. Toda e qualquer
          solicitação de dados de terceiros que estejam em poder da Kwadros em razão do contrato de prestação de serviços assinado com seus
          clientes está condicionada à requisição judicial; os dados armazenados não serão, sob qualquer hipótese, compartilhados por mera
          solicitação; em havendo a ocorrência de algum ilícito, civil, criminal ou administrativo, o interessado deverá proceder ao
          registro oficial da violação de seus direitos, pela forma prevista em lei, e encaminhar à Kwadros a solicitação com a competente
          ordem judicial ou de autoridade policial, do Ministério Público ou dos demais Poderes Constituídos que tenham legitimidade e poder
          para requisitar as informações armazenadas. <h4>8) MANUTENÇÃO DOS DADOS APÓS A EXCLUSÃO DA CONTA</h4> O Usuário poderá, a qualquer
          tempo, cancelar sua conta junto à Kwadros , bastando que acesse as Configurações da Plataforma, sendo ineficaz a utilização de
          qualquer outro meio para atingir tal objetivo. Havendo a solicitação direta do Usuário ao e-mail contato@kwadros.com, a Kwadros
          procederá ao arquivamento dos Dados Cadastrais e Pessoais fornecidos pelo Usuário ao longo da relação com a Kwadros , os quais
          serão mantidos em ambiente seguro e preservados para cumprimento dos artigos 7º, incisos II, V, VI e IX e 16, da Lei Geral de
          Proteção de Dados (Lei 13.709/18). Os registros de acesso (IP ́s), se existentes, serão descartados à medida que completarem 180
          dias de guarda, nos termos da legislação vigente. <h4>9) SPAM</h4> A Kwadros tem política contrária à promoção de Spam de qualquer
          espécie e tem o compromisso de assegurar que as mensagens enviadas pela Plataforma sejam sempre de interesse ou importância para
          os respectivos destinatários. Ademais, a qualquer momento o Usuário poderá optar por parar de receber e-mails da Kwadros ajustando
          suas preferências para recebimento de e-mails ou cancelando sua conta, como mencionado a cima. A Kwadros exige que seus Usuários
          não pratiquem spam, e que se certifiquem que as mensagens enviadas sejam sempre de interesse do destinatário. Condutas
          inapropriadas quanto a disseminação de spam sujeitará o Usuário a o cancelamento da conta, bem como a revelação dos dados
          cadastrais, nos termos desta Política de Privacidade.
        </p>
      </div>
    </Layout>
  );
}

export default Home;
