import React from 'react';
import Head from 'next/head';

import Layout from '@components/Layout/index';

function TermsOfUso() {
  return (
    <Layout>
      <Head>
        <title>Kwadros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pdf-container">
        <h1>Termos de uso</h1>
        <p>
          Vve comercio de artigos recreativos e decorativos ltda, CNPJ 42430077/0001-41 (aqui nessa página referida como “KWADROS”) oferece
          uma ferramenta que permite a você visualizar em tempo real suas fotos da galeria ou instagram em nossas molduras tamanho 20x20 cm,
          branca ou preta, com borda ou sem borda e efetuar a compra das mesmas. Cada pedido inclui, no mínimo, 3 peças, podendo ser
          adicionados quantos quadros desejarem. Os serviços estão disponíveis em nosso site https://www.kwadros.com. Esses termos se
          aplicam à todos os visitantes do site e usuários de nossos serviços. Por favor, leia esse documento com atenção, pois esses Termos
          de Serviço (“Acordo” ou “Termos”) e Nossa Política de Privacidade, encontrada em nosso site, descrevem o acordo legal entre Você
          (consumidor) e Nós. Esse Acordo foi desenvolvido pela Kwadros para descrever os termos do Seu uso dos Nosso site e produtos.
          Informações a respeito de como coletamos, usamos e compartilhamos os dados pessoais dos nossos usuários podem ser encontradas na
          nossa Política de Privacidade. Você reconhece e concorda que o seu acesso e uso dos sites e serviços e a aceitação dos termos aqui
          contidos estão sujeitos à nossa Política de Privacidade. Ao acessar os serviços, você concorda em seguir esse Acordo e que sua
          visita e/ou uso dos serviços e qualquer disputa que surja do mesmo, será governada pelos termos desse acordo. Nos reservamos o
          direito de modificar os termos desse acordo (incluindo a nossa Política de Privacidade) a qualquer momento. Sua aceitação e uso
          contínuo do site e/ou dos serviços implica a aceitação de todos os termos revisados e/ou adicionados aqui nesse Acordo. No
          entanto, recomendamos que você analise periodicamente a versão mais atualizada dos nossos Termos de Uso e Política de Privacidade
          através do nosso site. Caso você escolha não concordar e aceitar com os termos modificados ou acrescentados aqui nesse Acordo,
          você pode deixar de acessar o site e utilizar os serviços à qualquer hora. Se você não deseja aceitar as mudanças desse Acordo,
          sua única ação possível é deixar de utilizar nossos serviços. O Acordo modificado entra em vigência imediatamente após a postagem
          no site, a não ser que seja anunciado uma hora específica via uma eventual mensagem. Quaisquer mudanças nesse Acordo não serão
          aplicadas em disputas entre Nós e Você abertas numa data prévia às mudanças.
        </p>
        <h3>Serviços</h3>
        <p>
          Serviços oferecidos: oferece uma ferramenta que permite a você visualizar em tempo real suas fotos da galeria ou instagram em
          nossas molduras tamanho 20x20 cm, branca ou preta, com borda ou sem borda e efetuar a compra das mesmas. Cada pedido inclui, no
          mínimo, 3 peças, podendo ser adicionados quantos quadros desejarem. Garantias: Fazemos o melhor que podemos para entregar os
          melhores quadros para que você tenha uma excelente experiência desde o momento da escolha das fotos até o recebimento e inserção
          dos quadros na sua parede. Portanto, oferecemos garantia integral de 7 dias caso o produto não corresponda às suas expectativas
          ou, se em até 90 dias, apresentar qualquer tipo de problema, nos dispusemos a fazer a troca ou consertar, se possível.
        </p>
        <h3>Usuários (Consumidores) </h3>
        <p>
          Ao utilizar nossos serviços, você confirma que: (1) Você tem a autoridade e capacidade legal de entrar nesse Acordo e que (2) Você
          leu, compreendeu e concordou em se comprometer com os Termos, independente da plataforma ou dispositivo que você utiliza para
          acessar e comprar nossos produtos. Se você discordar desses termos, não deverá realizar a compra dos quadrinhos. Menores de idade
          O site e os serviços estão disponíveis apenas para indivíduos acima de dezoito (18) anos de idade. Ao aceitar esse Acordo, você
          concorda ter mais de 18 anos. A empresa não permite o uso dos serviços por pessoas que não tenham atingido a maioridade, assim
          como também não coleta dados conscientemente de pessoas abaixo de 13 anos.
        </p>
        <h3>Limitações dos usuários e moedas</h3>
        <p>
          A “Kwadros” se reserva no direito de limitar, revogar, suspender ou recusar pagamentos feitos por usuários de certos países ou
          localizações. Nós avisaremos os usuários que estiverem nessas localizações restritas.
        </p>
        <h3>Seu cadastro</h3>
        <p>
          Para criar a sua conta, basta você acessar nosso site e fazer o seu cadastro. Siga o passo a passo e faça seu pedido. Você será
          cobrado de acordo com o número de quadros escolhidos e os valores e demais informações estarão resumidas no carrinho de compras e
          na finalização do pagamento.
        </p>
        <h3>Cancelando sua conta</h3>
        <p>
          Você pode cancelar a sua conta a qualquer hora e por qualquer motivo acessando a parte de cadastro. Caso você precise de mais
          ajuda para cancelar a sua conta, envie um email para nosso suporte e responderemos dentro de 24 horas úteis. Nós reservamos o
          direito de armazenar, manter e usar as informações da sua conta e outros dados relevantes para motivos de negócios apenas
        </p>
        <h3>Informações da conta</h3>
        <p>
          Qualquer informação, incluindo Informações do Usuário e Informações da Conta fornecidas por você devem estar corretas, atualizadas
          e completas no momento de envio, a fim de evitar mal funcionamento. Você não deve compartilhar as informações da sua conta com
          terceiros. A confidencialidade dos dados da sua conta é unicamente de sua responsabilidade. Você deverá se responsabilizar por
          toda e qualquer atividade que ocorrer na sua conta ou com relação à ela Você deverá nos avisar imediatamente por escrito se
          acreditar que ocorreu algum acesso não-autorizado na sua conta ou se você achar que houve um vazamento das suas informações da
          conta. Não somos responsáveis por nenhum dano ou perda provenientes da sua falha em manter as informações da sua conta seguras ou
          de algum acesso não autorizado causados por você. Podemos, a qualquer momento, suspender, revogar ou limitar o seu direito de
          acessar os serviços caso você não siga os Termos de Uso desse acordo, seja qual for, ou se suspeitarmos que você não esteja de
          acordo com essa política.
        </p>
        <h3>Pagamentos</h3>
        <p>
          Os consumidores pagarão seus pedidos de acordo com a quantidade de quadros escolhidos e estes pagamentos ou reembolsos serão
          integralmente processados por intermediadores (gateways) de pagamentos seguros como “App Max” e “Pagar-me”. Nós da Kwadros não
          teremos acesso e nem armazenaremos dados de cartão ou qualquer outro dado sensível. Os dados que serão armazenados em nosso
          sistema, intermediado pela empresa YAMPI, serão: as fotos e os dados para emissão de nota fiscal e envio do pedido como nome
          completo, endereço, telefone, email e cpf. Por favor, veja os termos de uso e as políticas aplicáveis deles. Não nos
          responsabilizamos por problemas relacionados aos termos de uso dos gateway de pagamento. Podemos, ocasionalmente, mudar o nosso
          gateway de pagamento. Nosso sistema considera no cálculo os pedidos pagos dos últimos 7 dias (de segunda até domingo).
        </p>
        <h3>Suspensão do serviço</h3>
        <p>
          A Kwadros pode suspender o acesso, sem aviso prévio, de qualquer usuário, se: todas as tentativas de pagamentos das cobranças
          forem negadas. Fazemos até 4 tentativas por dia, recebermos algum tipo de chargeback em qualquer cobrança que tenhamos feito;
          detectarmos alguma violação dos nossos termos de uso; desrespeitar ou ser ofensivo com qualquer membro da Kwadros;
        </p>
        <h3>Garantia, licença, restrições e remoções.</h3>
        <p>
          Conteúdo de Usuário se refere a qualquer conteúdo, informação pessoal, informação empresarial, informação de produtos, informação
          delicada, informação da conta, aplicativos, trabalhos derivados, criados com base na nossa Propriedade Intelectual, APIs, códigos,
          imagens, testemunhos, logos, imagens de produto, análises ou outros materiais enviados ou inseridos na sua conta ou dados que
          usuários (incluindo você) enviam para serem utilizados nos serviços.
        </p>
        <h3>Garantia do conteúdo de usuário</h3>
        <p>
          Ao transmitir ou enviar qualquer Conteúdo do Usuário enquanto estiver usando os Serviços, Você afirma, representa, garante e
          confirma que tal transmissão ou envio seja (a) preciso e atualizado; (b) não viola quaisquer leis aplicáveis, restrições
          contratuais ou outros direitos de terceiros e que Você tenha permissão de terceiros cujas informações pessoais ou propriedade
          intelectual estejam incluídas no Conteúdo do Usuário; (c) livre de vírus, adware, spyware, worms ou outro código malicioso; e (d)
          Você reconhece e concorda que qualquer informação Sua em tal conteúdo será sempre processada por Nós de acordo com a nossa
          Política de Privacidade. Nós não seremos responsáveis por qualquer imprecisão ou deturpação, material e não material, do(s)
          produto(s) ou serviços vendidos por Vendedores aos seus Compradores. Qualquer fraude ou deturpação será considerada uma violação
          material deste Contrato.
        </p>
        <h3>Licença de uso do conteúdo de usuário</h3>
        <p>
          Ao transmitir ou enviar informações e fotos, Informações da Conta e Conteúdo do Usuário para os Serviços ou desenvolver e publicar
          conteúdo, Aplicativos e envios para o Site, Você mantém todos os direitos de propriedade intelectual e propriedade do Conteúdo do
          Usuário. Nenhuma transferência de propriedade é criada entre você e nós, para seu conteúdo de usuário ou vice-versa. Na medida do
          permitido pelas leis aplicáveis, Você concorda em não declarar contra nós quaisquer direitos morais que você possa ter em qualquer
          um dos seus conteúdos de usuário. Você concorda que podemos usar seu Conteúdo de usuário para marketing e promoções de serviços,
          desde que não usemos suas marcas registradas, informações pessoalmente identificáveis e informações confidenciais sem sua prévia
          aprovação por escrito. Os direitos que Você concede na Licença de Conteúdo do Usuário têm como objetivo operar, promover e
          melhorar nossos Serviços e desenvolver novos recursos, serviços e / ou produtos. Você deve ter os direitos necessários para nos
          conceder essa Licença de Conteúdo de Usuário para qualquer Conteúdo de Usuário que Você nos fornecer, direta e indiretamente. Você
          pode encontrar mais informações sobre como coletamos, usamos e armazenamos conteúdo em nossa Política de Privacidade
        </p>
        <h3>Atividades proibidas</h3>
        <p>
          A menos que você tenha o nosso consentimento expresso por escrito, você não deve, e não tentará: Utilizar nossos serviços para
          enviar, armazenar, transmitir ou processar códigos maliciosos, worms ou vírus; Carregar ou fornecer Conteúdo de Usuário falso,
          ilegal ou não autorizado, incluindo, mas não se limitando a, fazer declarações enganosas ou falsas para os Consumidores sobre
          produtos, intencionalmente apresentar preços errados e/ou vender intencionalmente os produtos errados, para Nossos Serviços; Usar
          nossos serviços para enviar, armazenar, transmitir ou processar conteúdo de usuário que seja ou possa ser: (a) ameaçador,
          ofensivo, degradante, odioso ou intimidante; (b) calunioso ou difamatório; (c) fraudulento, tortuoso ou ilegal; (d) obsceno,
          indecente, pornográfico ou de outra forma censurável; ou (e) infringir os direitos de qualquer pessoa, quaisquer leis aplicáveis
          ou Suas obrigações para com terceiros; Utilizar os nossos Serviços para enviar, armazenar, transmitir ou processar Conteúdo do
          Usuário que possa dar origem a responsabilidade criminal ou civil ou que incentive atividades ilegais; Obter acesso não autorizado
          aos nossos serviços, aos nossos sistemas ou redes; Interferir ou interromper a integridade ou o desempenho de nossos serviços ou
          conteúdo de terceiros contido nele; Fazer-se passar por qualquer pessoa ou entidade ou deturpar a sua afiliação com qualquer
          pessoa ou entidade relacionada com os nossos Serviços; Fazer engenharia reversa, desmontar ou descompilar nossos serviços ou
          aplicar qualquer outro processo ou procedimento para obter o código-fonte de qualquer software incluído em nossos serviços; Salvo
          exceções expressamente autorizadas por Nós, remover qualquer aviso de direitos autorais, marca registrada ou outros direitos de
          propriedade de nossos Serviços. dos produtos;
        </p>
        <h3>AVISO DE GARANTIA</h3>
        <p>
          ISENÇÃO DE GARANTIAS. O USO DOS NOSSOS SERVIÇOS É POR SUA CONTA E RISCO, E VOCÊ É O ÚNICO RESPONSÁVEL POR QUALQUER PERDA QUE
          RESULTE DE TAL USO. NOSSOS SERVIÇOS SÃO FORNECIDOS “COMO ESTÁ”. NÓS E NOSSOS LICENCIADORES, FORNECEDORES E CONTRATADOS, SE HOUVER,
          EXPRESSAMENTE REJEITAM TODAS AS GARANTIAS DE QUALQUER TIPO, SEJAM EXPRESSAS, IMPLÍCITAS OU OUTRAS, INCLUINDO AS GARANTIAS
          IMPLÍCITAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A UM DETERMINADO FIM, NÃO VIOLAÇÃO E QUALQUER GARANTIA DE TERCEIROS, INCLUINDO QUALQUER
          PARCEIRO. NEM NÓS, NEM NOSSOS LICENCIADOS, FAZEMOS QUALQUER GARANTIA DE QUE O SERVIÇO ATENDERÁ AOS SEUS REQUISITOS OU QUE O
          SERVIÇO SERÁ PRECISO, ININTERRUPTO, OPORTUNO, SEGURO OU SEM ERROS. NEM NÓS, NEM QUALQUER UM DOS NOSSOS LICENCIADOS, FAZEMOS
          QUALQUER GARANTIA QUANTO AOS RESULTADOS QUE PODEM SER OBTIDOS DO USO DO SERVIÇO, QUANTO À PRECISÃO, PONTUALIDADE, OU
          CONFIABILIDADE DE QUALQUER INFORMAÇÃO OBTIDA ATRAVÉS DO SERVIÇO, OU QUE OS DEFEITOS NO SERVIÇO EM TODO OU EM PARTE, INCLUINDO
          SOFTWARE, SERÃO CORRIGIDOS.
        </p>
        <h3>LIMITAÇÃO DE RESPONSABILIDADE</h3>
        <p>
          EM NENHUMA CIRCUNSTÂNCIA, SEREMOS RESPONSÁVEIS POR VOCÊ OU QUALQUER TERCEIRO POR QUAISQUER DANOS INDIRETOS, INCIDENTAIS, ESPECIAIS
          OU CONSEQUÊNCIAS RESULTANTES DO USO OU DA INCAPACIDADE DE USAR NOSSOS SERVIÇOS, INCLUINDO DANOS POR LUCROS CESSANTES, PERDA DE
          DADOS DE QUALQUER TIPO, MESMO SE TIVEREM SIDO AVISADOS DA POSSIBILIDADE DE TAIS DANOS. NÓS NÃO SEREMOS RESPONSÁVEIS POR DANOS DE
          QUALQUER TIPO, DIRETOS OU INDIRETOS, DECORRENTES OU DE QUALQUER FORMA RELACIONADOS AO SEU USO OU INCAPACIDADE DE USAR OS SERVIÇOS,
          INCLUINDO, MAS NÃO SE LIMITANDO A, DANOS ALEGADAMENTE DECORRENTES DA PERDA DE SUA CONTA, INFORMAÇÕES DE PAGAMENTO, OU PERDA OU
          INCAPACIDADE PARA RESTAURAR O ACESSO DE SEU BACKUP, OU POR ERROS, OMISSÕES, INTERRUPÇÕES, ATRASOS, DEFEITOS E/OU ERROS NA
          REALIZAÇÃO DE TRANSAÇÕES. ALÉM DISSO, NÃO SEREMOS RESPONSÁVEIS POR VOCÊ OU POR TERCEIROS POR QUAISQUER CONTEÚDOS DE TERCEIROS
          ENVIADOS OU BAIXADOS DO SITE OU PLATAFORMA. ALGUMAS DAS LIMITAÇÕES ACIMA PODEM NÃO SE APLICAR A VOCÊ. EM QUALQUER CASO, A
          RESPONSABILIDADE MÁXIMA DE NÓS A VOCÊ NÃO DEVE EXCEDER O VALOR LÍQUIDO DAS TAXAS PAGAS POR VOCÊ ATRAVÉS DO SERVIÇO DURANTE O
          PERÍODO DE TRÊS MESES IMEDIATAMENTE PRECEDENDO A DATA DE SUA RECLAMAÇÃO. Denúncias e violações aos Termos de Uso devem ser
          relatadas ao email contato@kwadros.com
        </p>
      </div>
    </Layout>
  );
}

export default TermsOfUso;
